<?php


namespace App\Enums;


class Questions
{
    const questions = [
        'How many hours can I record in the first semester?',
        'How many hours can I record in the second semester?',
        'How many hours can I record in the third semester',
        'How many hours can I record in the fourth semester?',
        'How many hours can I record in the fifth semester?',
        'How many hours can I record in the sixth semester?',
        'How many hours can I record in the seventh semester?',
        'How many hours can I record in the eighth semester?',
        'How many hours is first semester?',
        'How many hours is second semester?',
        'How many hours is third semester?',
        'How many hours is fourth semester?',
        'How many hours is fifth semester?',
        'How many hours is sixth semester?',
        'How many hours is seventh semester?',
        'How many hours is eighth semester?',
        'How many hours do I need to open the graduation project?',
        'How many credits do I need to graduate?',
        'How many credits for a Bachelor’s?',
        'How many credit hours does an introduction to computer course have?',
        'How many credit hours does an Electronics course have?',
        'How many credit hours does an English 1 course have?',
        'How many credit hours does a Fundamentals of Info Systems course have?',
        'How many credit hours does an English 2 course have?',
        'How many hours do I need to open the graduation project?',
        'How many credits do I need to graduate?',
        'How many credits for a Bachelor’s?',
        'How many credit hours does an introduction to computer course have?',
        'How many credit hours does an Electronics course have?',
        'How many credit hours does an English 1 course have?',
        'How many credit hours does a Fundamentals of Info Systems course have?',
        'How many credit hours does an English 2 course have?',
        'How many credit hours does a Math 1 course have?',
        'How many credit hours does a Physics course have?',
        'How many credit hours does a Principles of Management course have?',
        'How many credit hours does a Probability & Statistics course have?',
        'How many credit hours does a Programming Language 1 course have?',
        'How many credit hours does a principle of Economics course have?',
        'How many credit hours does an Algorithms course have?',
        'How many credit hours does a Business Law course have?',
        'How many credit hours does a Computer Architecture and Organization course have?',
        'How many credit hours does a Data Structures Course have?',
        'How many credit hours does a Database1 course have?',
        'How many credit hours does a Digital Logic Design course have?',
        'How many credit hours does a Discrete Structures course have?',
        'How many credit hours does a Mathematics (2) course have?',
        'How many credit hours does a Professional Ethics course have?',
        'How many credit hours does a Programming language (2) course have?',
        'How many credit hours does a Strategic Management course have?',
        'How many credit hours does a Visual Programming course have?',
        'How many credit hours does an Automata Theory course have?',
        'How many credit hours does a Computer Graphics course have?    ',
        'How many credit hours does a Computer Networks course have?',
        'How many credit hours does a Database System (2) course have?',
        'How many credit hours does a Feasibility Study course have?',
        'How many credit hours does a Mathematics (3) course have?',
        'How many credit hours does an Operating Systems (1) course have?',
        'How many credit hours do a Principles of Marketing course have?',
        'How many credit hours does a Project Managements course have?',
        'How many credit hours does a Report writing course have?',
        'How many credit hours does a System Analysis and Design course have?',
        'How many credit hours does a Systems Programming course have?',
        'How many credit hours does a Web Programming course have?',
        'How many credit hours does an Artificial Intelligence course have?',
        'How many credit hours does a Computer Networks 2 course have',
        'How many credit hours does a Creative Thinking course have?',
        'How many credit hours does a Data Mining course have?',
        'How many credit hours does an Image Processing course have?',
        'How many credit hours does an Information Security course have',
        'How many credit hours does a Machine Learning course have?',
        'How many credit hours does a Mobile Programming course have?',
        'How many credit hours does an Operation Research course have',
        'How many credit hours does a Software Engineering course have?',
        'What is Credit Hours system?',
        'What is the meaning of a “Credit hour”?',
        'How is my academic performance measured in the credit hours system?',
        'What is the GPA?',
        'How many credit hours am I going to study per semester?',
        'What are the differences between credit hours system and the regular one?',
        'What is Credit Hours system?',
        'Academic advisor',
    ];

    const answers = [
        '16 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '16 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '18 Hours',
        '102 Hours',
        '136 Hours',
        '136 Hours',
        '4 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '4 Hours',
        '3 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '4 Hours',
        '3 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '4 Hours',
        '4 Hours',
        '3 Hours',
        '3 Hours',
        '2 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        '3 Hours',
        'Simply you are required to get done with 180 Credit hours system in a minimum of 4 years and maximum of 10 years.',
        'A Credit hour is a unit that gives weight to the value, level or time requirements of an academic course taken.
            The number of credit hours for each course is 2 or 3 credit hours so you are having almost like 60 courses during university.',
        'Academic performance is measured by GPA.',
        'GPA is a number with a minimum of Zero and maximum of 4.0 where if you got A As you will get a 4.00 and if you got D you will get 1.00',
        'If you are supposed to finish university in 4 years you will study 16 in first semester and 18 credit hours all per semester, unless your GPA gets lower than 2.00 so you will study only 12 which means that more than semester below 2.00 will definitely mean that you are going to graduate later than your friends!',
        'Mainly credit hours system programmed needs more attention and work throughout the year as 60% of the grading depends on course work (course work is about quizzes and midterms ).
            Passing in credit hours system requires scoring 60% or more unlike the regular system which is 50%.
            Classes in credit hours system all is taught in English unlike the regular system.',
        'Simply you are required to get done with 180 Credit hours system in a minimum of 4 years and maximum of 10 years.',
        'The academic advisor is a staff member or a teaching assistant who is assigned the supervision of a group of students in addition to guiding and helping them in choosing what is appropriate to their abilities and interests',
        ];

}
